name: Kwik Bandit
favicon: null
layout_spectrum: 0.14345
typography_spectrum: 0.387
title: Banding the World Together
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1397e9'
    - '#ffffff'
    - '#d2ebfa'
    - '#45aded'
    - '#83c8f2'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
