name: Kwik Bandit
favicon: null
layout_spectrum: 0.7334596603177488
typography_spectrum: 0.7494320482946932
title: Banding the World Together
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1397e9'
    - '#ffffff'
    - '#d2ebfa'
    - '#45aded'
    - '#83c8f2'
  brandStrength: 0.3125
  lightness: 0.7224448705092072
  saturation: 0.2942796724382788
  rhythmicContrast: 0.3194346586242318
purpose: []
